go:
    cgo: false
repository:
    path: github.com/lovoo/ipmi_exporter
build:
    flags: -a -tags 'netgo static_build'
    ldflags: |
        -s
        -X {{repoPath}}/vendor/github.com/prometheus/common/version.Version={{.Version}}
        -X {{repoPath}}/vendor/github.com/prometheus/common/version.Revision={{.Revision}}
        -X {{repoPath}}/vendor/github.com/prometheus/common/version.Branch={{.Branch}}
        -X {{repoPath}}/vendor/github.com/prometheus/common/version.BuildUser={{user}}@{{host}}
        -X {{repoPath}}/vendor/github.com/prometheus/common/version.BuildDate={{date "20060102-15:04:05"}}
crossbuild:
    platforms:
        - linux/amd64
        - linux/386
        - linux/arm
        - linux/arm64
        - darwin/amd64
        - darwin/386
        - freebsd/amd64
        - freebsd/386
        - netbsd/amd64
        - netbsd/386
        - windows/amd64
        - windows/386
