language: go
go:
  - 1.7

script:
  - make build
  - make test

before_deploy:
  - gem install fpm package_cloud
  - make release-build deb release-package

deploy:
  provider: releases
  api_key:
    secure: bGQ5GCSKAoZaMD+AI25cG1dDdRGRG1V4GjF0AKTsE+bgvfrLkCLfjrPf4K9wWzqh6ztEju3bRdMdu4cDqaX5N4rRmdGtjkt7H0A1V1h8tORv36gbIPXEmM+47hUgu3wysvayr1Ok1edWGTMqzX5M/EyAWdzlBw410+jccil3X280T5VSotiY7V7nxc3dnL91Z8JCFz7Nf422oVHq8ZQZHGTruazImsne8bo92BIl+vH/EtFVu5+H6EGPeNowOEBTOu9HpcpLaDF3LePmPMwfh1wvGCDjie4PTzbA/LyN89T+IPuqlMUUj9E7wSh4Q0n1e4MmaCmeYRU/CeoS5NBJ2Kfg6OP/+ZQsr7tIeWRvwBYpN3dA3M4sUZzo3qGFcJ5J1ZliBNl5+L0aX3WuiMgI8LQQ2cZyitjhv7TyChjLCpGoQu0ZWaNwcGlx5SFMt03fbIikywidJTZj9fkLVB1lRoSLRkP0i
  file:
    - build/ipmi_exporter_darwin_amd64
    - build/ipmi_exporter_freebsd_386
    - build/ipmi_exporter_freebsd_amd64
    - build/ipmi_exporter_linux_386
    - build/ipmi_exporter_linux_amd64
    - build/ipmi_exporter_linux_arm
    - build/ipmi_exporter_linux_arm64
    - build/ipmi_exporter_windows_386.exe
    - build/ipmi_exporter_windows_amd64.exe
  on:
    repo: lovoo/ipmi_exporter
    tags: true
